services:
  app:
    build: ./app
    restart: always
    expose:
      - 8000
    networks:
      - internal

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - default
      - internal

networks:
  default:
  internal:
    internal: true

volumes:
  gz_data:
  caddy_data:
  caddy_config:
